### ISSUE TITLE
Custom GUI elements are not being hidden while zoomed in

### ISSUE THREAD

**Issue by squ1b3r** [fuami/Spyglass#3]
I'm working on a mod that adds a custom stats bar that is registered the same way the game registers other GUI elements:

```c#
 capi.Gui.RegisterDialog(new HudElementAirBar(capi));
```

Due to how hiding UI elements is implemented right now those custom elements will stay visible while using the Spyglass. The game itself hides those just fine when using `.gui` command, pressing `F4`, or changing the game mode to `Spectator`.

I did a little bit of digging and it seems like all you need to do is to find a way to set `ClientMain.ShouldRender2DOverlays` to `false` and the game will handle the rest. I tried to find a way to do that but my C# is a bit rusty so I gave up. I found this however, where ApacheTechSolutions uses reflections to set that value. Maybe that will give you some ideas.

**Comment by fuami** [comment]
I'll have to think on this. I think the reason I didn't go in this direction is because it also hides my "spy glass overlay." That said, I'd simply not considered modded gui elements also being in play. So I will probobly have to re-consider this.

**Comment by squ1b3r** [comment]
> because it also hides my "spy glass overlay."

Oh, right. Didn't think about that. 

In any case, thank you for looking into it, and let me know if you need more information. I haven't released it yet but here is how I register that custom statsbar in my mod - https://github.com/squ1b3r/vs-oxygen-not-included/blob/main/src/OxygenNotIncludedMod.cs#L33

**Comment by fuami** [comment]
I think you closed this by accident :D

**Comment by squ1b3r** [comment]
> I think you closed this by accident :D

Thank you! I totally did close this by accident. Today is just not my day.

**Comment by fuami** [comment]
[spyglass_v0.4.4.zip](https://github.com/fuami/Spyglass/files/7946976/spyglass_v0.4.4.zip)
Could you confirm if this build fixes the compatibility issue with your mod? I think I've worked out a suitable fix, and if so I'll go ahead and release this.

**Comment by squ1b3r** [comment]
> [spyglass_v0.4.4.zip](https://github.com/fuami/Spyglass/files/7946976/spyglass_v0.4.4.zip) Could you confirm if this build fixes the compatibility issue with your mod? I think I've worked out a suitable fix, and if so I'll go ahead and release this.

Yes! It worked perfectly!

**Comment by fuami** [comment]
Glad to hear it!

**Comment by squ1b3r** [comment]
Thank you for fixing this so quickly. :shipit:
